# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dba532d7ef39c1affd948f8d507508d7"
name = "ReportesAPI"
application_url = "https://shopify-reports-app.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_analytics,read_customers,read_orders,read_products,read_reports"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://shopify-reports-app.onrender.com/auth/callback" ]

